#server:
#  port: 8761
# application configuration
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
    org.springframework.cloud: DEBUG

eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 5

#spring:
#  application:
#    name: eureka-server
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false